import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  // Пользователь по умолчанию
  const user = await prisma.user.upsert({
    where: { id: 'default-user-id' },
    update: {},
    create: {
      id: 'default-user-id',
      email: 'test@aiitsolar.pro',
      username: 'testuser',
      name: 'Test User',
    },
  });

  // Проект по умолчанию
  const project = await prisma.project.upsert({
    where: { id: 'default-project-id' },
    update: {},
    create: {
      id: 'default-project-id',
      name: 'AI IT Solar Demo',
      description: 'Seed project for local dev',
      language: 'JavaScript',
      isPrivate: false,
      userId: user.id,
    },
  });

  // (опционально) Пример ревью, чтобы эндпоинты сразу что-то отдавали
  await prisma.review.upsert({
    where: { id: 'default-review-id' },
    update: {},
    create: {
      id: 'default-review-id',
      title: 'Initial review',
      description: 'Generated by seed',
      oldCode: 'console.log("old");',
      newCode: 'console.log("new");',
      language: 'JavaScript',
      riskLevel: 'LOW',
      status: 'PENDING',
      projectId: project.id,
      userId: user.id,
    },
  });

  console.log('✅ Seed completed');
}

main()
  .catch((e) => {
    console.error('Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
